BATCH_SIZE = 512

DATASET_SAMPLES_PER_IMAGE = 500

RAW_DATASET_PATH = "raw_compose_base_images_dataset"
DATASET_PATH = "compose_base_images_dataset"

MODEL_PATH = "model.safetensors"

MODEL_HALF_IMAGE_SIZE = (80, 80)
MODEL_IMAGE_SIZE = (MODEL_HALF_IMAGE_SIZE[0], MODEL_HALF_IMAGE_SIZE[1] * 2)
IGNORE_BORDERS_X = 400
