wrap_comments = true
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
