TEST_IMAGES_PATH = "test_images"
TEST_MAPS_PATH = "test_maps"

PIXELS_PER_TILE = 20

COLLISION_TILES_PER_MAP_TILE = 10  # used for pathfinding

DISTANCE_TO_WAYPOINT_EPS = (
    0.1  # unit distance to waypoint to consider it visited
)

FPS = 60

MAX_ATTACK_DURATION = 180.0

# colors
DROP_ZONE_TILE_EVEN_COLOR = "#324628"
DROP_ZONE_TILE_ODD_COLOR = "#1E1E0A"
DROP_ZONE_BORDER_TILE_EVEN_COLOR = "#324600"
DROP_ZONE_BORDER_TILE_ODD_COLOR = "#1E1E00"

TILE_EVEN_COLOR = "#282828"
TILE_ODD_COLOR = "#0A0A0A"
BORDER_TILE_EVEN_COLOR = "#1E3C00"
BORDER_TILE_ODD_COLOR = "#141E00"

BUILDING_TILE_EVEN_COLOR = "#785800"
BUILDING_TILE_ODD_COLOR = "#402F00"

COLLISION_TILE_COLOR = "#FF0000"
