from pygame.color import Color


BASE_WIDTH = 44
BASE_HEIGHT = 44
MAP_BORDERS = 3

MAP_WIDTH = BASE_WIDTH + MAP_BORDERS * 2
MAP_HEIGHT = BASE_HEIGHT + MAP_BORDERS * 2

PIXELS_PER_TILE = 20

COLLISION_TILES_PER_MAP_TILE = 10  # used for pathfinding

DISTANCE_TO_WAYPOINT_EPS = (
    0.1  # unit distance to waypoint to consider it visited
)

# colors
DROP_ZONE_TILE_EVEN_COLOR = Color(50, 70, 40)
DROP_ZONE_TILE_ODD_COLOR = Color(30, 30, 10)
DROP_ZONE_BORDER_TILE_EVEN_COLOR = Color(50, 70, 0)
DROP_ZONE_BORDER_TILE_ODD_COLOR = Color(30, 30, 0)

TILE_EVEN_COLOR = Color(40, 40, 40)
TILE_ODD_COLOR = Color(10, 10, 10)
BORDER_TILE_EVEN_COLOR = Color(30, 60, 0)
BORDER_TILE_ODD_COLOR = Color(20, 30, 0)

BUILDING_TILE_EVEN_COLOR = Color(120, 88, 0)
BUILDING_TILE_ODD_COLOR = Color(64, 47, 0)

COLLISION_TILE_COLOR = Color(255, 0, 0)
