[package]
name = "webserver"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
cocsim = { path = "../cocsim" }
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["full"] }
tracing-subscriber = "0.3.19"
