[package]
name = "webserver"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
cocsim = { path = "../cocsim" }
inventory = "0.3.20"
nalgebra = "0.33.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["full"] }
tracing-subscriber = "0.3.19"
