[package]
name = "cocsim-fuzz-target"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
afl = "0.15"
arbitrary = { version = "1", features = ["derive"] }
cocsim = { path = "../cocsim" }
