[package]
name = "cocsim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
enum_dispatch = "0.3.13"
nalgebra = { version = "0.33.2", features = ["serde-serialize"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
shipyard = { version = "0.8.1", default-features = false, features = ["proc", "std"] }
zip = "4.3.0"
