[package]
name = "cocsim"
version = "0.1.0"
edition = "2024"

[dependencies]
enum_dispatch = "0.3.13"
inventory = "0.3.20"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
