[package]
name = "showcase"
version = "0.1.0"
edition = "2024"

[dependencies]
cocsim = { path = "../cocsim" }
image = { version = "0.24", default-features = false, features = ["jpeg"] }
macroquad = "0.4"
